version: "3.9"

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=demo_db
      - DATABASE_USER=demo_user
      - DATABASE_PASSWORD=demo_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/1

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # persistent storage

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
